services:
  redis:
    image: "redis:my-store"
    ports:
      - "6379:6379"
  web:
    # build:
    #   context: .
    #   dockerfile: packages/server/Dockerfile
    image: rohan-lather/whatsapp-clone:latest
    ports:
      - "4000:4000"
    environment:
      - REDIS_HOST=redis
      - DATABASE_URL=postgres://postgres:angela@localhost:5001/whatsapp
  db:
    image: postgres
    ports:
      - "5001:5001"
    environment:
      - POSTGRES_PASSWORD=angela
